server:
  port: 3344
spring:
  application:
    name: cloud-config-center  #注册进eureka服务器的微服务名
  cloud:
    config:
      server:
        git:
          uri: https://github.com/maize-j/springcloud-config.git  #github上面的git仓库名字
          search-paths:
            - springcloud-config  #搜索目录
      label: master  #读取分支
#服务注册到eureka地址
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka