server:
  port: 9527
spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true  #开启从注册中心动态创价路由的功能，利用微服务名进行路由
      routes:
        - id: payment_route    #路由的ID，没有固定规则但要求唯一，建议配合服务名
#          uri: http://localhost:8001    #匹配后提供服务的路由地址
          uri: lb://cloud-payment-service  #匹配后提供服务的路由地址，使用微服务名称时，连接了VPN会报错Caused by: java.net.SocketException: Permission denied: no further information
          predicates:
            - Path=/payment/getPaymentById/**    #断言，路径相匹配的进行路由http://localhost:8001/payment/getPaymentById/**

        - id: payment_routh2    #路由的ID，没有固定规则但要求唯一，建议配合服务名
#          uri: http://localhost:8001    #匹配后提供服务的路由地址
          uri: lb://cloud-payment-service  #匹配后提供服务的路由地址
          predicates:
            - Path=/payment/lb/**    #断言，路径相匹配的进行路由
#            - After=2020-09-10T10:00:00.215+08:00[Asia/shanghai]   #在设定时间之后路由才生效，格式为java.time包中的ZonedDateTime
#            - Before=2020-09-10T11:00:00.215+08:00[Asia/shanghai]    #在设定时间之前路由生效
#            - Between=2020-09-10T10:00:00.215+08:00[Asia/shanghai],2020-09-10T11:00:00.215+08:00[Asia/shanghai]   #在设定时间之间路由生效
#            - Cookie=username, maize  #username表示cookie的名称，maize为cookie的值，可以是正则表达式  测试时可以用cmd访问curl http://localhost:9527/payment/lb?uname=123 --cookie "username=maize"，用powershell会报错
#            - Header=X-Request-Id, \d+  #请求头要有X-Request-Id属性，并且值为整数（正则表达式）
#            - Method=Get   #必须为get请求
#            - Query=username, \d+  #要有参数名username并且值还要是整数才能路由
#            - Host=**.com.yz  #主机名称
#          filters:
#            - AddRequestHeader=X-Request-Id,111  #过滤器官网在匹配的请求头上加上这一对请求头，这种是单一的filter，针对单个路由的过滤器，全局路由见MyGatewayFilter，需要实现GlobalFilter, Ordered接口

eureka:
  instance:
    hostname: cloud-gateway-service
  client:  #服务提供则provider注册进eureka服务列表中
    service-url:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://eureka7001.com:7001/eureka
