server:
  port: 3344
spring:
  application:
    name: cloud-config-center  #注册进eureka服务器的微服务名
  cloud:
    config:
      label: main #读取分支
      server:
        git:
          uri: https://github.com/maize-j/SpringCloudStudy.git  #github上面的git仓库名字
          search-paths:
            - config  #搜索目录,https://github.com/maize-j/SpringCloudStudy.git地址下的config文件夹
#服务注册到eureka地址
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka