#端口号
server:
  port: 7001
eureka:
  instance:
    hostname: eureka7001.com  #eureka服务端的实例名称
  client:
    #false表示不向注册中心注册自己
    register-with-eureka: false
    #false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    fetch-registry: false
    service-url:
      #设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址
#      defaultZone: http://eureka7002.com:7002/eureka/  #集群版，在7001上面注册7002
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    #关闭自我保护机制，保证不可用服务被及时剔除
    #自我保护是指在否一个时刻，入驻进来的某个服务不可用时，eureka也不会立即清除，依然保存他的信息
    enable-self-preservation: false
    #清理无效服务的间隔时间，默认时间修改为2秒
    eviction-interval-timer-in-ms: 2000
