server:
  port: 80

#Eureka
eureka:
  client:
    #表示是否将自己注册进EurekaServer，默认为true
    register-with-eureka: true
    service-url:
      #注册地址
      #      defaultZone: http://localhost:7001/eureka   #单机版
      defaultZone: http://eureka7002.com:7001/eureka,http://eureka7001.com:7002/eureka  #集群版

#设置feign客户端超时时间（OpenFeign默认支持ribbon）
ribbon:
  #指的是建立连接所用的时间，适用于网络状态正常的情况下，两端连接所用的时间，单位是毫秒
  ReadTimeout: 5000
  #指的是建立连接后从服务器读取到可用资源所用的时间
  ConnectTimeout: 5000
logging:
  level:
    #feign日志以什么级别监控哪个接口
    cn.yz.springcloud.service.PaymentFeignService: debug
