server:
  port: 8001

#微服务名称
spring:
  application:
    #入驻进Eureka服务器的名称
    name: cloud-provider-hystrix-payment

#Eureka
eureka:
  client:
    #表示是否将自己注册进EurekaServer，默认为true
    register-with-eureka: true
    #表示是否从EurekaServer中抓取已有的注册信息，默认为true，单节点无所谓，集群必须设置为true才能默认ribbon使用负载均衡
    fetch-registry: true
    service-url:
      #注册地址
#      efaultZone: http://localhost:7001/eureka   #单机版
#      defaultZone: http://eureka7002.com:7001/eureka,http://eureka7001.com:7002/eureka  #集群版
      defaultZone: http://eureka7001.com:7001/eureka